#add_newline = false

prompt_order = [
    "time",
#    "username",
#   "hostname",
    "custom.shore",
#    "kubernetes",
    #"env_var",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
#    "hg_branch",
#    "docker_context",
    "package",
#    "dotnet",
#    "elixir",
#    "elm",
#    "erlang",
#    "golang",
#    "java",
#    "julia",
#    "nim",
#    "nodejs",
#    "ocaml",
#    "php",
#    "purescript",
    "python",
    "ruby",
    "rust",
#    "terraform",
#    "zig",
#    "nix_shell",
#    "conda",
    "memory_usage",
    "aws",
#    "crystal",
    "cmd_duration",
#    "custom",
    "line_break",
    "jobs",
    "custom.hostname_win",
    "custom.hostname_mac",
    "custom.hostname",
    "directory",
#    "battery",
    "character",
]

[env_var]
variable = "SHORE_PROJECT_TITLE"
symbol = ""

[custom.hostname_mac]
command = "echo Macbook"
when = """ test -d /Applications """

[custom.hostname_win]
command = "echo Arcade"
when = """ test -d /mnt/c/WINDOWS """

[custom.hostname]
command = "hostname -s"
when = """ test ! -d /Applications -a ! -d /mnt/c/WINDOWS """

[custom.shore]
command = "echo $SHORE_PROJECT_TITLE"
when = """ test -n "$SHORE_PROJECT_TITLE" """

