add_newline = true

format = """
$time\
${custom.shore}\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$ruby\
$rust\
$memory_usage\
$cmd_duration\
$line_break\
$jobs\
${custom.hostname_win}\
${custom.hostname_mac}\
${custom.hostname}\
$directory\
$line_break\
$character"""

[env_var]
variable = "SHORE_PROJECT_TITLE"
symbol = ""

[custom.hostname_mac]
command = "echo Macbook"
when = """ test -d /Applications """

[custom.hostname_win]
command = "echo Arcade"
when = """ test -d /mnt/c/WINDOWS """

[custom.hostname]
command = "hostname -s"
when = """ test ! -d /Applications -a ! -d /mnt/c/WINDOWS """

[custom.shore]
command = "echo $SHORE_PROJECT_TITLE"
when = """ test -n "$SHORE_PROJECT_TITLE" """

[character]
error_symbol = "[✗](bold red)"
